; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltecv4_dev]
platform = espressif32
; board = heltec_wifi_lora_32_V4
board = esp32dev
framework = arduino
lib_deps = 
	knolleary/PubSubClient@^2.8
	vshymanskyy/TinyGSM@^0.12.0
	vshymanskyy/StreamDebugger@^1.0.1
	; heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5
; board_build.variants_dir = variants
; board_build.variant = heltec_V4

monitor_speed = 115200  
monitor_dtr = 0
monitor_rts = 0
build_unflags = -std=gnu++11 -std=c++11 -std=c++14
build_flags = -std=gnu++17